apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-external-ext4-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: zerofs-external-ext4
---
apiVersion: v1
kind: Pod
metadata:
  name: fio-external-ext4
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: fio
    image: alpine:3.22.2
    command: ["sh", "-lc"]
    args:
    - |
      set -euo pipefail
      apk add --no-cache fio >/dev/null

      run() {
        name="$1"
        shift
        echo "=== ${name} ($(date -Is)) ==="
        fio --output-format=json --output=/tmp/${name}.json "$@"
        cat /tmp/${name}.json
        echo
      }

      run prefill_write_1m_endfsync \
        --name=prefill_write_1m_endfsync \
        --filename=/data/testfile \
        --size=512m \
        --rw=write \
        --bs=1m \
        --direct=1 \
        --iodepth=32 \
        --numjobs=1 \
        --end_fsync=1 \
        --group_reporting \
        --eta=never

      run randwrite_4k_fsync1 \
        --name=randwrite_4k_fsync1 \
        --filename=/data/testfile \
        --size=512m \
        --rw=randwrite \
        --bs=4k \
        --direct=1 \
        --iodepth=1 \
        --numjobs=1 \
        --fsync=1 \
        --time_based \
        --runtime=45 \
        --group_reporting \
        --eta=never

      run randwrite_4k_iodepth32 \
        --name=randwrite_4k_iodepth32 \
        --filename=/data/testfile \
        --size=512m \
        --rw=randwrite \
        --bs=4k \
        --direct=1 \
        --iodepth=32 \
        --numjobs=4 \
        --time_based \
        --runtime=45 \
        --group_reporting \
        --eta=never

      run randread_4k_iodepth32 \
        --name=randread_4k_iodepth32 \
        --filename=/data/testfile \
        --size=512m \
        --rw=randread \
        --bs=4k \
        --direct=1 \
        --iodepth=32 \
        --numjobs=4 \
        --time_based \
        --runtime=45 \
        --group_reporting \
        --eta=never
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: fio-external-ext4-pvc
