apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-soak-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: zerofs-test
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-soak
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: fio
        image: alpine:3.22.2
        command: ["sh", "-lc"]
        args:
        - |
          set -euo pipefail
          apk add --no-cache fio >/dev/null

          echo "=== fio soak start ($(date -Is)) ==="
          fio --name=soak_randrw_4k_fsync16 \
            --output-format=json \
            --output=/tmp/soak_randrw_4k_fsync16.json \
            --filename=/data/testfile \
            --size=2g \
            --rw=randrw \
            --rwmixread=70 \
            --bs=4k \
            --direct=1 \
            --iodepth=8 \
            --numjobs=2 \
            --fsync=16 \
            --time_based \
            --runtime=3600 \
            --group_reporting \
            --eta=never

          cat /tmp/soak_randrw_4k_fsync16.json
          echo "=== fio soak end ($(date -Is)) ==="
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fio-soak-pvc
