apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: default
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-12-18T13-15-44Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
  namespace: default
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: output
        image: minio/mc:RELEASE.2024-11-21T17-21-54Z
        command: ["/bin/sh", "-c"]
        args:
        - |
          until mc alias set myminio http://minio:9000 minioadmin minioadmin; do echo waiting for minio...; sleep 1; done;
          mc mb myminio/zerofs || true;
